### ISSUE TITLE
Problem importing Dataset

### ISSUE THREAD

**Issue by mic7010** [flexyford/impagination#38] opened 2017-06-20 16:29 UTC
When importing the Dataset I am getting an error 

'Unable to resolve module 'util' from node-modules/binary-search-tree/lib/avltree.js'

I am running 0.44.1 of React Native

**Comment by ricwa230** [comment] 2017-07-01 23:07
I had the same problem and it is because the node-util module does not exist in RN. A quick fix that worked for me was simply `npm install util` or `yarn add util`. Hope this info helps you.

**Comment by cowboyd** [comment] 2017-10-30 18:40
Looks like this is a duplicate of #40

**Closed** 2017-10-30 19:55 UTC
